name: docker

#on: [push]

# 在master分支发生push事件时触发。
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

env: # 设置环境变量
  TZ: Asia/Shanghai # 时区

jobs:
  build: # 自定义名称
    runs-on: ubuntu-latest # 运行在虚拟机环境ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - name: Checkout # 步骤1
        uses: actions/checkout@v1 # 使用的动作。格式：userName/repoName。作用：检出仓库，获取源码。 官方actions库：https://github.com/actions
      - name: Use Node.js ${{ matrix.node-version }} # 步骤2
        uses: actions/setup-node@v1 # 作用：安装nodejs
        with:
          node-version: ${{ matrix.node-version }} # 版本
      - name: 部署到腾讯云服务器
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude="" --include="" --filter=""
          path: ''
          remote_path: /var/www/blog_vuepress/
          remote_host: 49.232.222.252
          remote_port: 22
          remote_user: root
          remote_key: ${{ secrets.TOKEN }}
      #执行命令
      - name: execute shell
        uses: appleboy/ssh-action@master
        with:
          host: 49.232.222.252
          username: root
          key: ${{ secrets.TOKEN }}
          port: 22
          script: |
            # 删除运行的容器
            docker stop $(docker ps -qa --filter name=vuepress)
            docker rm $(docker ps -qa --filter name=vuepress)
            # 构建
            cd /var/www/blog_vuepress
            docker-compose down
            docker-compose build --no-cache
            docker-compose up -d
